// Generated by CoffeeScript 1.8.0
(function() {
  var i, _i;

  for (i = _i = 1; _i <= 98; i = ++_i) {
    if (i > 48 && i < 57 || i >= 65 && i <= 90 || i >= 97 && i <= 122) {
      console.log(i);
    }
  }

}).call(this);
