// Generated by CoffeeScript 1.7.1

/*
Read a file from file system, then count its lines. in synchronous.
 */

(function() {
  var contents, fs, _ref, _ref1;

  fs = require('fs');

  contents = (fs.readFileSync((_ref = (_ref1 = process.argv) != null ? _ref1[2] : void 0) != null ? _ref : 'test.txt')).toString();

  console.log((contents.match(/\n/g)).length);

}).call(this);
