// Generated by CoffeeScript 1.7.1

/*
@author rankun203@gmail.com

coffee arguments training.
add all arguments together.
 */

(function() {
  var i, num, sum, _i, _len, _ref;

  sum = 0;

  _ref = process.argv;
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    num = _ref[i];
    if (i > 1) {
      sum += +num;
    }
  }

  console.log(sum);

}).call(this);
