// Generated by CoffeeScript 1.7.1

/*
Read a file from file system, then count its lines. in asynchronous.
 */

(function() {
  var fs, _ref, _ref1;

  fs = require('fs');

  fs.readFile((_ref = (_ref1 = process.argv) != null ? _ref1[2] : void 0) != null ? _ref : 'test.txt', function(err, contents) {
    var contStr;
    contStr = contents.toString();
    return console.log((contStr.match(/\n/g)).length);
  });

}).call(this);
