// Generated by CoffeeScript 1.7.1

/*
 *@author rankun203@gmail.com
 *
 *Module: list filtered files
 */

(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  module.exports = function(folder, ext, callback) {
    return fs.readdir(folder, function(err, files) {
      var file, filteredFiles, _i, _len;
      if (err) {
        return callback(err, files);
      }
      filteredFiles = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if ((path.extname(file)) === ("." + ext)) {
          filteredFiles.push(file);
        }
      }
      return callback(null, filteredFiles);
    });
  };

}).call(this);
