// Generated by CoffeeScript 1.7.1

/*
List files with specified extension in a specified folder.
 */

(function() {
  var ext, folder, fs, reg, _ref, _ref1;

  fs = require('fs');

  folder = (_ref = process.argv[2]) != null ? _ref : './';

  ext = (_ref1 = process.argv[3]) != null ? _ref1 : '.*';

  reg = new RegExp("^.*\." + ext + "$");

  fs.readdir(folder, function(err, files) {
    var file, _i, _len, _results;
    if (err) {
      throw err;
    }
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if (file.match(reg)) {
        _results.push(console.log(file));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
