// Generated by CoffeeScript 1.7.1
(function() {
  var Guitar, Instrument, guitar,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Instrument = (function() {
    function Instrument(type) {
      this.type = type;
    }

    Instrument.prototype.sound = function() {
      return console.log("" + this.type + " sound");
    };

    return Instrument;

  })();

  Guitar = (function(_super) {
    __extends(Guitar, _super);

    function Guitar() {
      Guitar.__super__.constructor.call(this, "Guitar");
    }

    return Guitar;

  })(Instrument);

  guitar = new Guitar();

  guitar.sound();

}).call(this);
